apiVersion: apps/v1
kind: Deployment
metadata:
  name: trovu-deploy
spec:
  selector:
    matchLabels:
      app: trovu
  template:
    metadata:
      labels:
        app: trovu
    spec:
      containers:
      - name: trovu
        image: wylswz/trovu:0.1.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
---

apiVersion: v1
kind: Service
metadata:
  name: trovu-service
spec:
  selector:
    app: trovu
  ports:
  - port: 8081
    targetPort: 8081
